### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by scramble45** [Tylian/ffxiv-cap#1]
````
C:\ffxiv-cap\lib\Capture.js:15
        const linkType = c.open(device, 'tcp and port ' + port, bufSize, buffer);
                           ^

TypeError: device must be a string
    at TypeError (native)
    at Capture (C:\ffxiv-cap\lib\Capture.js:15:28)
    at Object.<anonymous> (C:\ffxiv-cap\index.js:20:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
````

**Comment by scramble45** [comment]
as far as I can tell device is a string in my index.js

**Comment by Tylian** [comment]
I've had this issue as well, and I think it's Windows Firewall related.

What happens is, pcap tries to enumerate the available devices, but can't find any matching the string provided so it returns undefined, thus throwing the not a string error.

I usually fix it by opening and closing ACT, lol.

That said, it's happened enough that I should probably add an error message for it.
